### ISSUE TITLE
Add The Snowcat Web Browser

### ISSUE THREAD

**Issue by VeryUsual** [ZeroX-DG/awesome-browser#1]
Website: https://snowcat.codeberg.page/
Repo: https://codeberg.org/snowcat/snowcat

**Comment by ZeroX-DG** [comment]
Could you open a PR for this?

**Comment by VeryUsual** [comment]
sure

**Comment by ZeroX-DG** [comment]
Added in https://github.com/ZeroX-DG/awesome-browser/pull/2
